### PR TITLE
Remove all the stuff moving over to vivarium public health

### PR DESCRIPTION
**Pull request by collijk**

### CODE REVIEW

**Comment by robmoss** [comment]
The file `disease.py` in `vivarium_public_health.mslt` is empty.

**Comment by robmoss** [comment]
I copied over `disease.py` from the `mslt_port` repository and updated the script that generated the data artifact. When I run the `tobacco_test.yaml` simulation (but pulling in data from the artifact), the results differ from those obtained when using the `mslt_port.data` module. Will investigate ...

**Comment by robmoss** [comment]
The simulation that uses the data artifact results in one extra year of life for each strata --- they reach age 110, while using `mslt_port.data` they only reach age 109. So this is why the life expectancy differs even though the population size and person years at each year do not. I did have to make some modifications to the vph.mslt module. What's the best way of sharing them? Should I commit them to the `mslt_port` branch of vph?

**Comment by collijk** [comment]
Yeah, you can commit directly here.  As soon as the thing works as you expect it, we'll merge the mslt branch into the main branch of public health and then we can use a normal branch and merge workflow for any new code or documentation that needs to come in.

**Comment by robmoss** [comment]
So I've sorted out everything (except for the extra year of life when using VPH.mslt). I tried pushing the commits to the `feature/mslt_port` branch of VPH, but it instead creates a new remote branch called `mslt_port` even though I've set the upstream branch correctly. I have to use `git push origin HEAD:feature/mslt_port` instead.

**Comment by collijk** [comment]
That's super weird.  Let me look at the extra year of life thing.  I think I know where it's coming from.

**Comment by collijk** [comment]
Just pushed a change that should fix the age bit.

**Comment by robmoss** [comment]
And now it's producing identical simulation output!

**Comment by collijk** [comment]
You want to merge these two branches then?  We can start moving docs stuff over as appropriate and start shaping this one into more of the data manipulation and results repo.

**Comment by robmoss** [comment]
Yep, all done.

**Pull request merged**
